djangotutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from views import AboutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', AboutView.as_view(), name='index'),
    url(r'^python/', include('python.urls'), name = 'python'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

python/urls.py
from django.conf.urls import url
from . import views

app_name = 'python'

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

python/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

djangotutorial/views.py
from django.views.generic import TemplateView

class AboutView(TemplateView):
    template_name = "index.html"

python/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html', {})

templates/base.html
{% load staticfiles %}

<html>
    <head>
        <title>
            {% block title %}
                Base Site
            {% endblock title %}
        </title>
        {% block static %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
            <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
            <link rel="stylesheet" type="text/css" href="{% static 'css/devicon.min.css' %}" />
            <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
            <script src="{% static 'js/tether.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.js' %}"></script>
            <script src="{% static 'js/vue.js' %}"></script>
        {% endblock static %}
    </head>
    <body>
        {% block nav %}
            <div id="app">
                <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
                    <div class="container">
                        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <a class="navbar-brand" href="javascript:;">
                            <i class="devicon-python-plain colored"></i>
                            Portfolio
                        </a>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'index' %}">
                                        Home
                                        <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:;">
                                        Profile
                                        <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'python:home' %}">
                                        Python
                                        <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        {% endblock nav %}

        {% block content %}{% endblock content %}

        {% block vue %}
            <script type = "text/javascript">
                new Vue({
                    el: '#app',

                    data: {
                        message: ''
                    },

                    delimiters: ["<%","%>"]
                })
            </script>
        {% endblock vue %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}Python home{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="jumbotron" style="background-color:black;">
            <h2 align="center" style="color:white;">Manjil Shrestha</h2>
            <h1 align="center" style="color:white; font-size: 50px;">Python Programmer</h1>
            <p style="color:white; text-align:justify;">
                Welcome to digital portfolio. This is where I showcase all the cool stuff that I have enjoyed working
                recently and I share a little bit about my personal life too.
            </p>
            <div align="center">
                <a href="https://fb.com/pratiman69"><button type="button" class="btn btn-outline-primary">Facebook</button></a>
                <a href="https://github.com/smanjil"><button type="button" class="btn btn-outline-secondary">Github</button></a>
                <a href="https://www.linkedin.com/in/manjil-shrestha-038527b4/"><button type="button" class="btn btn-outline-primary">LinkedIn</button></a>
                <a href="https://stackoverflow.com/users/6254981/smanjil"><button type="button" class="btn btn-outline-info">Stack Overflow</button></a>
            </div>
        </div>
        <p>This is some text.</p>
        <p>This is another text.</p>
    </div>
{% endblock content %}